### ISSUE TITLE
How to install??

### ISSUE THREAD

**Issue by Joherca** [runescapejon/PokeTextures#15]
Hi is it posible to do this in survival mode, if not or if yes, how can i use this plugin??
Thanks

**Comment by runescapejon** [comment]
Yes you can

Here how to create a resourcepack https://pixelmonmod.com/wiki/index.php?title=Custom_textures
this is a way to create your own textured pokemon

 Commands are `/ptgive <pokemon> <PlayerName> <Value>` now, for example, the value means the `Custom-ghost` in your texture pack and it would be `/ptgive Lugia runescapejon ghost`.

and there an chance to spawn a custom texture pokemon within the config also

**Comment by Joherca** [comment]
I mean in single player mode, because i have pixelmon 7.2.0 and your PokeTexture in the mod folder, and a texture pack with custom textures, but when i use the command, the game said this command doesnt exist type help...

**Comment by runescapejon** [comment]
That because it's require to have SpongeForge installed. Luckily spongeforge does support client singleplayer usage. All you have to do is download SpongeForge in your mods folder with Poketexture and then launch your game. Then your all set.

Here a link to SpongeForge https://www.spongepowered.org/downloads/spongeforge/stable/1.12.2

**Comment by Joherca** [comment]
okokok thaaaaaaaanks a looot i could make it, now i wanna know, if its possible to have more than one texture pack?
